# GitHub Actions의 액션 탭에서 표시되는 워크플로우 이름
name: Build Only

on:
  # develop 브랜치에 push나 PR이 들어오면 워크플로우 실행
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-15

    steps:
      # GitHub 레포지토리 소스 체크아웃
      - uses: actions/checkout@v4

      # 사용할 수 있는 Xcode 버전 출력
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      # 현재 선택된 Xcode 버전 확인
      - name: Show current version of Xcode
        run: xcodebuild -version

      # 원하는 Xcode 버전 설정
      - name: Set up Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
          xcodebuild -version

      # Xcode 프로젝트 빌드
      - name: Build the project 🛠
        run: |
          xcodebuild clean build \
            -project CaloLink.xcodeproj \
            -scheme CaloLink \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -skipPackagePluginValidation -skipMacroValidation
